### ISSUE TITLE
Implement system `alalc-guj-gijr-latn-1997` (ALA-LC Romanization Table -- Gujerati (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#99] opened 2020-01-09 13:36 UTC
This issue is to implement the transliteration system of alalc-guj-gijr-latn-1997.

This system is referred in the GeoNames database as `guj_Gijr2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Gujerati (1997)'.

 Tests should rely on the data extracted for the `guj_Gijr2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by bilashsaha** [comment] 2020-11-12 05:55
Closing as duplicate of https://github.com/interscript/interscript/issues/539

**Closed as completed by bilashsaha** 2020-11-12 05:55 UTC
Labels: enhancement
