### ISSUE TITLE
Fix Mongolian old script exceptional cases (UN Mongolian)

### ISSUE THREAD

**Issue by abunashir** [interscript/interscript-ruby#37] opened 2019-12-22 14:17 UTC
The [Mong-Latn-2013](https://github.com/riboseinc/interoperable-transliteration/blob/master/maps/un-mon-Mong-Latn-2013.yaml#L83) includes some test to handle an exceptional city name, but there were no rules specified, and this was failing our test suite.

We've added a temporary mapping to solve that unique case for now, but it would be amazing if a native could dobule check and come up with some well-defined rules for those exceptional cases.

cc: @ronaldtse

**Comment by ronaldtse** [comment] 2020-09-17 00:55
The problem with `kökeqota` is at https://github.com/interscript/interscript/blob/fdc760394f0b7446e3b96d76ab5ad28b0bd06e67/maps/un-mon-Mong-Latn-2013.yaml#L99

Clarification from UNGEGN:
> The encoding of Mongolian script is really complex and is based more on phonology rather than the script itself. You might find more information in KNAB's version of the romanization table at http://www.eki.ee/knab/lat/kblcmg2.pdf, particularly in comments to characters 12–13 at the end.

> If you look at the Unicode character names in ᠬᠥᠬᠡᠬᠣᠲᠠ (kökeqota) you'll get Q+OE+Q+E+Q+O+T+A. The name consists of two words, the first of which is köke ('blue'), as the vowels (OE, E) in this word are front vowels and the consonants are usually transliterated k, not q in this case. The second word is qota ('city') and in this case the vowels are back vowels which explains the use of q, not k.

> [T]he Mongolian script itself makes a distinction between k and q but the encoding unites these into one character... [...] The Mongolian script is quite unique in the sense that you cannot read it unless you already know the exact reading of ambiguous characters. And the encoding is based on pronunciation, not the logic of the script itself.

We may need to use a seq2seq approach (https://github.com/secryst) to achieve this without special cases.

**Comment by ronaldtse** [comment] 2020-09-29 08:52
Closing this because `kökeqota` is actually not a transliteration of the UN system, it is from the system in #482! Glad that this is confirmed.

**Closed as completed by ronaldtse** 2020-09-29 08:52 UTC
